<a href="https://colab.research.google.com/github/robertosgpontes/tec_prog_1/blob/main/ExerciciosNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lista de Exercícios de Numpy

Deverá ser entrege até **11/02/2023** por meio do github que foi informado por vocês no [formulário](https://forms.office.com/r/YV12vEXGYF) respondido na aula de 01/02.

A entrega pela github é parte da avaliação.

In [1]:
import numpy as np

## Questão 1

Crie um array 100 com valores aleatórios e ache os valores máximo e mínimo

In [226]:

q1 = np.random.randint(0, 500, size=100)
print(q1)
print(f'O número máximo é {np.max(q1)}')
print(f'O número mínimo é {np.min(q1)}')

[211 111 403 112 135 140 444 464 316 110  80 404 339 359 489  93 388  92
  41 167 278 492 238 410 416  88 396 109 137 469  60 235 328 387 109 389
 114 297  12 212 406 190 153 280  69 116 469 172 378 386 142 173  36 180
  54 488  82 151 164 332 400 310 215 456 164 328 368 264 209 304 271 105
 400 418 230 478  85 376 443 466 182 179  14 476 285 245 279  26 331  23
 483 138 150 197 468 483 404 160 111  72]
O número máximo é 492
O número mínimo é 12


## Questão 2
Em Geometria Analítica, um **vetor** é uma quantidade que pode ser definida por um énuplo (uma sequência ordenada de *n* elementos) em que cada elemento representa a intensidade do vetor na direção especificada pela i-ésima componente desta sequência. 

Quando pensamos em duas dimensões, por exemplo, o vetor $R = (b,a)$ define, geometricamente, a entidade representada na figura abaixo, com componentes nos eixos x e y usuais.

<img src = "https://static.todamateria.com.br/upload/im/ag/image-721.jpg?auto_optimize=low" />

O **módulo** deste vetor, também chamado de intensidade, está geometricamente relacionado ao seu comprimento, e pode ser calculado diretamente pelas suas componentes, por meio de uma operação conhecida como **produto escalar** do vetor com ele mesmo. O módulo quadrático é expresso, desta forma, por:

$|A|^2 = \vec{A} \cdot \vec{A}$

Por outro lado, o produto escalar entre dois vetores $A = (a_{x}, a_{y})$ e $B = (b_{x}, b_{y})$ é dado por:

$\vec{A} \cdot \vec{B} = a_{x} \times b_{x} + a_{y} \times b_{y}$ (e esta definição vale para qualquer que seja a dimensão do vetor).

O módulo quadrático de um vetor é, portanto:

$|A|² = a_{x}^2 + b_{x}^2$.

Dado o exposto acima, escreva uma função que retorne o módulo de um vetor n-dimensional qualquer.

In [228]:
def modulo_vetor (q2):
    m = q2**2
    soma = np.sum(m)
    modulo = soma**0.5
    return modulo

#Exemplos de arrays
x1 = np.array([1, 1, 1])
x2 = np.array([3 , 4])
x3 = np.array([4, 5, 7, 8])
modulo_vetor(x2)


5.0

## Questão 3

Em uma **análise de regressão**, usualmente estamos interessados em descrever relações entre variáveis de um dado conjunto de dados por meio de uma **função** que descreva, o tanto quanto possível, estas relações.

Por exemplo, no gráfico abaixo, os pontos vermelhos relacionam as medidas das duas variáveis sendo avaliadas (nos eixos x e y); e a linha azul aproxima a relação entre elas por uma função linear.

![Normdist_regression.png](https://miro.medium.com/v2/resize:fit:786/format:webp/1*LEmBCYAttxS6uI6rEyPLMQ.png)

É possível ver que nem todos os pontos obedecem exatamente à relação ditada pela reta (isto é, há pontos que não estão exatamente "sobre a reta"; mas, sim, ligeraimente acima, ou abaixo, dela). Isto, contudo, é esperado em um modelo de regressão, por inúmeras fontes de incerteza associadas às medições.

Uma das métricas que utilizamos para avaliar a qualidade de uma regressão é o **erro quadrático médio (EQM)**, que mensura a diferença total entre cada predição da regressão ($y_{prediction}$; que no nosso caso seriam os valores de y para a reta azul) com o valor real de cada i-ésima medida ($y_{i}$; que no nosso caso seriam as coordenadas y para cada ponto vermelho do gráfico). O EQM pode ser definido como:

$EQM = \frac{1}{n}\sum_{i=1}^{n}(y_{prediction} - y_{i})^2$.

Isto posto, escreva uma função que calcule o EQM recebendo, como entrada, os vetores $y_{prediction}$ e $y_{i}$. Por exemplo, digamos que sua função se chame *calculate_eqm*, ela deve operar da seguinte forma:

```python

# dados dois arrays quaisquer de mesmo tamanho, a função deve retornar o EQM
y_prediction = np.array([1,2,3])
y_i = np.array([0,0,3])
calculate_eqm(y_prediction,y_i)

>>> 1.6666666666666665

```

In [229]:
# Solução
#Célula de teste
q3_1 = np.array([1,2,3])
q3_2 = np.array([0,0,3])

In [230]:
def calculate_eqm(y_prediction, y_i):
    x = np.size(y_prediction)
    soma, dif = 0, 0
    for i in range(x):
        dif = (y_prediction[i]-y_i[i])**2
        soma += dif
    eqm = soma/x
    return eqm
print(f'O EQM é: {calculate_eqm(q3_1, q3_2):.4f}!')

O EQM é: 1.6667!


## Questão 4

Crie um array 2D (bidimensional) com 1 na borda e 0 dentro

In [231]:
q4 = np.array([[1, 1, 1, 1, 1], [1, 0, 0, 0, 1], [1, 0, 0, 0, 1],[1, 0, 0, 0, 1], [1, 1, 1, 1, 1]])
q4

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

## Questão 5

Como adicionar uma borda de 0's ao redor de um array 2D (bidimensional) existente

In [232]:
print(q4)
q5 = np.pad(q4, pad_width=1, mode='constant', constant_values=0)
print(q5)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
[[0 0 0 0 0 0 0]
 [0 1 1 1 1 1 0]
 [0 1 0 0 0 1 0]
 [0 1 0 0 0 1 0]
 [0 1 0 0 0 1 0]
 [0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0]]


## Questão 6

 A eletroencefalografia (EEG) é uma técnica que mensura potenciais elétricos cerebrais em diversas regiões do escalpo do paciente. Suponha que você recebeu um conjunto de dados na forma de uma matriz de 64 x 512 elementos, em que cada linha contém o sinal gravado em um dos **eletrodos** espalhados pelo escalpo em um exame de EEG, e cada coluna contém um valor de potencial elétrico, em microvolts. 

Como o sinal de EEG é muito suscetível a ruídos externos (interferências na qualidade do sinal), uma operação comum para atenuar a interferência no sinal consiste em tirar a média do potencial elétrico de todos os eletrodos, e subtrair este valor de cada um deles. Isto atenua fontes de ruído ao sinal comuns a todos os eletrodos. Em termos matemáticos, o sinal processado por esta operação, $X_{e,i}$ para cada eletrodo (e) e amostra (i), é dado por:

$X_{e,i} = \hat{X_{e,i}} - \frac{1}{N}\sum_{e=1}^{N}\hat{X_{e,i}}$,

em que $\hat{X_{e,i}}$ representa o sinal original (ou seja, é a matriz de entrada de 64 x 512 elementos), e $N$ indica o total de eletrodos.

Com o exposto acima, escreva uma função que retorne uma matriz com os sinais de EEG processados conforme a operação mencionada. Sua função deve operar conforme o exemplo abaixo.

```python

# vamos supor uma matriz de entrada gerada por dados aleatórios
X = np.random.randn(64,512)
X.shape # apenas para verificar as dimensões
>>> (64, 512)

# a função deve executar a operação equacionada anteriormente, retornando uma nova matriz
X_processado = process_EEG_signal(X)
X_processado.shape
>>> (64, 512)

# Somando as diferenças entre cada elemento das duas matrizes, apenas para ilustrar que elas não são iguais
(X_processado - X).sum()
>>> -53.08727366483029

# Visualizando as matrizes, para verificar uma vez mais que, de fato, os elementos são diferentes
X
>>> array([[ 0.29305925,  0.89663038, -0.61032202, ..., -0.88086364,
        -0.8818789 ,  0.51260497],
       [-0.01274415,  1.05439522,  0.47958092, ..., -2.15387924,
         0.70721168,  0.97029889],
       [ 1.09478371, -0.16120847,  1.58400361, ...,  0.20981813,
         2.17373837,  0.94032162],
       ...,
       [-0.45294842, -2.28939505,  1.10111998, ...,  1.63581703,
        -0.39394924, -1.13400723],
       [-0.22669886,  0.25413429, -1.17870637, ..., -0.09509442,
         0.90733806,  0.37999411],
       [ 0.15476933, -0.03654717, -1.09982762, ...,  0.67600047,
        -0.84533328, -0.56433144]])

# Matriz após o processamento descrito no enunciado
X_processado

>>> array([[ 0.36713022,  0.85772513, -0.54902169, ..., -0.85626087,
        -0.97611435,  0.51718998],
       [ 0.06132682,  1.01548997,  0.54088126, ..., -2.12927647,
         0.61297623,  0.97488389],
       [ 1.16885469, -0.20011372,  1.64530394, ...,  0.23442091,
         2.07950292,  0.94490663],
       ...,
       [-0.37887744, -2.3283003 ,  1.16242031, ...,  1.6604198 ,
        -0.4881847 , -1.12942223],
       [-0.15262788,  0.21522904, -1.11740604, ..., -0.07049164,
         0.81310261,  0.38457911],
       [ 0.22884031, -0.07545242, -1.03852729, ...,  0.70060324,
        -0.93956874, -0.55974643]])

```

In [233]:
# Solução
q6 = np.random.randn(64,512)
def process_EEG_signal(variavel_q6):
    tratando_q6 = np.sum(variavel_q6)
    media = tratando_q6/np.size(variavel_q6)
    tratado_q6 = variavel_q6 - media
    print(np.shape(tratado_q6))
    return tratado_q6

print(q6)
process_EEG_signal(q6)

[[-0.73447101 -0.13689187 -0.83053227 ...  0.85572272  0.46367309
  -0.47119533]
 [-0.50144663  1.40532557 -0.92687307 ...  1.14123905  0.1103927
  -0.32516892]
 [ 0.02387097  0.61589747  1.61943878 ...  2.38631443 -0.74508409
   0.09307027]
 ...
 [-1.67151987 -1.62752618 -0.5293175  ...  0.11403537 -0.40012168
  -0.53807254]
 [-0.77315191  0.16862768 -0.6578909  ... -0.84742016  1.42667511
   0.89480986]
 [ 0.58383967  0.06059553  0.99465566 ...  0.47406104 -0.02525108
  -0.07923112]]
(64, 512)


array([[-0.73776939, -0.14019024, -0.83383065, ...,  0.85242435,
         0.46037472, -0.47449371],
       [-0.50474501,  1.40202719, -0.93017145, ...,  1.13794067,
         0.10709433, -0.3284673 ],
       [ 0.0205726 ,  0.6125991 ,  1.6161404 , ...,  2.38301606,
        -0.74838246,  0.0897719 ],
       ...,
       [-1.67481824, -1.63082456, -0.53261587, ...,  0.110737  ,
        -0.40342006, -0.54137091],
       [-0.77645028,  0.1653293 , -0.66118927, ..., -0.85071854,
         1.42337674,  0.89151149],
       [ 0.5805413 ,  0.05729716,  0.99135729, ...,  0.47076267,
        -0.02854946, -0.0825295 ]])

## Questão 7

Em estatística, um **outlier** é um valor que destoa consideravelmente da distribuição à qual está associado. Um dos critérios para idenficar outliers consiste em encontrar a **distância interquantil** (IQR), ou seja, a diferença entre o terceiro (Q3) e o primeiro quartis (Q1) da distribuição, e tomar como outliers todos os pontos abaixo do Limite Inferior (LI = Q1 - 1.5*IQR  ), ou acima do Limite Superior (LS = Q3 + 1.5*IQR).

![image.png](https://s3-sa-east-1.amazonaws.com/lcpi/0d8a7b04-b982-4e6b-9fc7-fbb062247d8d.png)


<img src = "https://blog.curso-r.com/images/posts/banner/outlier.webp" />

Escreva uma função que, dada uma matriz de dados de entrada de dimensões $N_{observações} \times N_{features}$ retorne três requisitos: 
- uma matriz booleana indicando a existência de outliers nos dados de entrada;
- a quantidade de outliers
- quem são os outliers (os valores).

**Algumas definições:**
- um *quantil* divide a distribuição, após ordenados os pontos, segundo algum ponto de corte;
- o **primeiro quartil** é o ponto para o qual 25 % dos valores da distribuição estão abaixo dele;
- o **terceiro quartil** é o ponto para o qual 75 % dos valores da distribuição estão abaixo dele.

Pode ser útil consultar a função **numpy.quantile**.

Exemplo de operação da função:

```python
# Geremos um conjunto de dados qualquer
X = np.random.randn(300,15)
X

>>> array([[-2.02108952,  0.57945921, -2.23074965, ..., -0.60349514,
         0.92180452, -0.15625722],
       [ 0.24904397,  0.03493447,  0.3515052 , ..., -0.46950081,
         0.20361331,  0.02715956],
       [ 0.55902525, -0.48435434,  0.90413414, ..., -0.54425743,
        -0.80769134, -0.07912549],
       ...,
       [-1.04069388, -0.24245725, -2.00308877, ...,  0.4084777 ,
        -1.81516131,  0.39063118],
       [-1.39275097,  0.3989636 ,  0.2926223 , ...,  1.2620666 ,
         0.72262949,  1.50737559],
       [ 0.15922011, -0.79810788, -1.60939896, ..., -0.08214499,
        -0.13167475,  0.15990558]])


# identificamos os requisitos com nossa com nossa função "locate_outliers"
is_outlier, outliers_count, outliers = locate_outliers(X)

is_outlier
>>> array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

outliers_count
>>> 44

outliers
>>> array([-2.67240384,  3.00270904,  3.62317101,  3.18867865,  2.55581522,
       -2.82091429,  2.8757892 ,  2.70666036,  3.19514999, -3.40550318,
       -3.39825827,  2.6727295 ,  2.54498296, -2.69447104,  3.19521603,
        2.66372172, -2.77444948,  2.77421152,  2.69992869, -2.84831109,
       -2.83695779, -2.45908227,  3.07802106,  2.89314015, -2.68574682,
       -2.85019494,  2.43399574,  2.44291266, -2.92595937, -2.95911074,
       -3.03966003,  2.77543068, -2.67368414, -2.79965402, -3.0501958 ,
       -2.5437387 ,  3.08550649, -3.17666255, -3.05795476, -3.09826467,
        3.1399469 ,  3.18141942,  2.90564257, -2.89505054])

 ``` 

In [234]:
# Solução
q7 = np.random.randn(300,15)

def locate_outliers(mx_q7):
    mediana = np.median(mx_q7)
    q1 = np.quantile(mx_q7, 0.25)
    q3 = np.quantile(mx_q7, 0.75)
    q7_iqr = q3-q1
    limite_inf = q1 - (1.5*q7_iqr)
    limite_sup = q3 + (1.5*q7_iqr)
    contador = 0 
    tamanho = np.shape(mx_q7)
    lst = np.array([])
    lst2 = []
    mx_bool = np.copy(mx_q7).astype('bool')
    mx_bool_at = ~mx_bool
    for x in mx_q7:
        for y in x:
            if (y<limite_inf or y>limite_sup):
                contador += 1
                lst = np.append(lst, y)
                b = np.where(mx_q7==y)
                lin = int(b[0])
                col = int(b[1])
                lst2.append([lin, col])
    for z in range(len(lst2)):
        mx_bool_at[lst2[z][0]][lst2[z][1]] = True
        print(mx_bool_at)
    return f'O número de outliers é {contador}', (f'A lista de outliers é: {lst}')
print(q7)
locate_outliers(q7)

[[ 0.55016935  0.68265212  0.16894009 ...  0.56714171  0.33685305
   0.25880868]
 [ 0.31783809 -0.42785533  0.31782863 ... -0.90961625 -0.07925197
  -0.1424589 ]
 [-1.14047192 -0.63155187  0.15977802 ...  2.09109626  1.00836359
  -0.07984398]
 ...
 [ 1.64209996  0.88178753 -0.25125078 ... -0.51818335 -1.53405896
  -0.397955  ]
 [-1.50935473  0.16849273  1.71525735 ... -0.5016302   0.58000325
  -1.09149207]
 [-2.06092365  0.89057244 -1.5803694  ...  0.44641871  0.06924439
   1.82646418]]
[[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]
[[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... 

('O número de outliers é 22',
 'A lista de outliers é: [ 3.51056387  2.91178242 -2.80310941  2.8644768  -2.78321526  2.93089275\n -3.83578265  2.97671134  3.65027628  3.85904543 -3.29115601  2.99829106\n -3.37529199 -2.91973898  2.81966303  3.40282308  2.74703667  2.82597319\n  2.74852736 -3.0312024   2.80344994 -2.86708909]')

## Questão 8

Crie um vetor com valores que vão de 1 até 21 de dois em dois, a partir da função arange

In [235]:
q8 = np.arange(1, 22, 2)
q8

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

## Questão 9

Crie um array de 10 com valores aleatórios

In [236]:
q9 = np.random.randint(0, 500, size=10)
q9

array([116, 441,  71,  42, 288, 277, 397, 111,  42, 256])

## Questão 10

Em estatística, a normalização de uma distribuição de dados pode ser feita subtraindo o valor médio da distribuição de cada valor do conjunto de dados, dividindo o resultado pelo desvio-padrão da distribuição. Escreva uma função que normalize os dados recebidos por um array numpy qualquer, conforme descrito anteriormente.

In [237]:
q10 = np.random.rand(100)*10
print(q10)
def normalizacao(var_q10):
    media = np.mean(var_q10)
    desvio = np.std(var_q10)
    q10_fin = np.array([])
    for i in range(np.size(var_q10)):  
        q10_fin = np.append(q10_fin, (var_q10[i]-media)/desvio)
    print(q10_fin)
normalizacao(q10)


[5.4433223  7.91935948 6.7138579  2.38683307 6.86462285 4.30764062
 6.3875469  6.09831852 3.13445654 1.21335139 2.72577392 5.63185268
 7.25951394 2.10405544 1.62666569 6.00113195 9.09365513 0.98862049
 5.57542187 9.05335126 5.31180545 0.03030416 9.69348221 7.12948578
 0.41826593 4.09049554 2.1381563  9.56555682 7.71129588 3.65676349
 5.84184789 9.61469077 2.62262168 2.84177418 2.29889545 3.44428571
 5.38427478 5.8102474  1.68298963 3.45744143 2.1269972  7.4062784
 9.72541369 5.19003892 3.22254342 8.14265401 3.98186904 3.83708804
 5.04230605 1.2382116  7.88280459 6.87868139 0.28978888 0.15943937
 7.92728848 0.59360442 5.71071621 3.28965369 9.35049712 7.94565139
 2.89499941 3.65212198 4.01978056 2.94208365 4.25654042 8.01590794
 4.2191717  3.09748461 7.04200368 2.27728237 3.33526794 4.06115642
 0.27565312 4.68667595 7.37992739 8.02506301 3.37437614 3.33818594
 5.47034137 9.6707091  0.08469425 5.67382078 3.775014   2.17029814
 7.34156778 3.07753827 8.10543195 8.83447813 1.94880403 6.40558

## Questão 11

Escreva uma função em numpy que receba um array contendo notas de uma turma de 100 estudantes. Considere que a nota de aprovação da turma é 5.0. A função deve retornar, em um array numpy, nesta ordem:
- a média e o desvio-padrão das notas da turma;
- o número de notas maiores que 7.0;
- o número de reprovações da turma;
- a menor nota da turma;
- a maior nota da turma.

In [238]:
q11 = np.random.rand(100)*10
print(q11)

[2.97127575 0.1690584  7.00115171 1.27019003 4.48369605 5.1614636
 8.54928071 2.04507641 2.85175063 0.8781776  4.60599902 0.17844671
 9.52853788 6.50199753 3.61260933 9.76941117 4.7398301  3.60775724
 0.23918217 1.9038592  5.80591762 8.01224076 5.34479578 8.39139299
 5.42084259 2.26657175 3.74979643 0.85495632 0.38534225 2.45798287
 9.50205664 4.11475416 5.36226615 7.28887003 3.57156401 1.67396268
 1.32097912 2.76828127 3.43101445 4.19402541 6.04664573 7.86681305
 8.73413621 6.42228051 6.63737889 3.77759178 2.54496317 5.38089483
 7.60139387 2.2715378  8.85621886 8.11655057 0.79350037 6.35398382
 2.25677713 7.41032917 7.89032416 9.35425116 2.06366934 3.75332817
 5.07126432 8.10589965 1.77194908 3.05178281 2.84429672 0.266333
 1.27410992 4.09353335 0.63928957 6.10894669 8.88108888 3.65674908
 2.59812977 6.94088388 0.9239005  0.81580033 4.81987799 2.14231315
 2.05391756 7.22641695 0.42589419 4.92500277 0.93763484 4.29906083
 1.05755343 5.96571758 8.1465533  6.5348932  0.4769122  5.8324356